general.import = ["~/.config/alacritty/colors.toml", "~/.config/alacritty/fonts.toml"]
general.live_config_reload = true

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations = "full"
dynamic_title = true
# history = 1000
# multiplier = 3
startup_mode = "Windowed"
opacity = 0.75

[terminal.shell]
program = "/bin/bash"
args = ["--login"]

[window.dimensions]
columns = 114
lines = 40

[window.padding]
x = 10
y = 10
